services:
  phpapp:
    build: 
      context: .
    volumes:
      - "./:/var/www/html"
    ports:      
      - 8080:80
      - 8443:443

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306